Codetag.Web/Models/ServerViewModel.cs
namespace Codetag.Web.Models
{
	using System.ComponentModel.DataAnnotations;

	public class ServerViewModel
	{
		public ServerViewModel()
		{
			MaxValue = 100;
		}

		[Display(Name = "Fake Server Name")]
		[Required]
		public string ServerName { get; set; }

		[Required]
		[Range(10, 100)]
		[Display(Name = "Maximum Random Value for Y Axis")]
		public int MaxValue { get; set; }
	}
}

Codetag.Web/Controllers/ServerController.cs
using System.Web.Mvc;

namespace Codetag.Web.Controllers
{
	using System.Diagnostics;
	using System.Threading;

	using Codetag.Web.Models;

	public class ServerController : Controller
	{
		// GET: /Server/Create

		public ActionResult Create()
		{
			var newServer = new ServerViewModel();
			return View(newServer);
		}

		//
		// POST: /Server/Create

		[HttpPost]
		public ActionResult Create(ServerViewModel newServer)
		{
			try
			{
				string tcpClientFileName = Server.MapPath("/TcpExes") + @"/Codetag.TcpClient.exe";
				var arguments = "\"" + newServer.ServerName + "\" " + newServer.MaxValue.ToString();

				ProcessStartInfo startInfo = new ProcessStartInfo();
				startInfo.UseShellExecute = true;
				startInfo.FileName = tcpClientFileName;
				startInfo.WindowStyle = ProcessWindowStyle.Normal;
				startInfo.Arguments = @arguments;

				Thread.Sleep(500);

				Process.Start(startInfo);
				Session["ServerName"] = newServer.ServerName;
				return RedirectToAction("Create");

			}
			catch
			{
				return View();
			}
		}
	}
}

Codetag.Web/Views/Server/Create.cshtml
@model Codetag.Web.Models.ServerViewModel

@section headScripts
{
	<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="~/Scripts/excanvas.min.js"></script><![endif]-->
	@*<script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>*@
	<link href="~/Content/examples.css" rel="stylesheet" type="text/css" />
}

@{
	ViewBag.Title = "Main Page - Servers";
}

<div id="content"></div>
<div class="demo-container">
	<div id="placeholder" class="demo-placeholder"></div>
</div>

<h2>Create a new Server</h2>

@using (Html.BeginForm()) 
{
	@Html.AntiForgeryToken()
	@Html.ValidationSummary(true)

	<fieldset>
		<legend>ServerViewModel</legend>

		<div class="editor-label">
			@Html.LabelFor(model => model.ServerName)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.ServerName)
			@Html.ValidationMessageFor(model => model.ServerName)
		</div>

		<div class="editor-label">
			@Html.LabelFor(model => model.MaxValue)
		</div>
		<div class="editor-field">
			@Html.EditorFor(model => model.MaxValue)
			@Html.ValidationMessageFor(model => model.MaxValue)
		</div>

		<p>
			<button type="submit">Create</button>
		</p>
	</fieldset>
}

@*<div>
	@Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts 
{
	@Scripts.Render("~/bundles/jqueryval")

	<script src="~/Scripts/jquery.flot.min.js" type="text/javascript"></script>
	<script src="~/Scripts/jquery.flot.time.min.js" type="text/javascript"></script>
	<script src="~/Scripts/jquery.flot.axislabels.js" type="text/javascript"></script>
	<script type="text/javascript">

		var data = [];
		var dataset;
		var totalPoints = 100;
		var updateInterval = 1000;
		var now = new Date().getTime();
		var serverName = '@Session["ServerName"]';

		var myData = [];
		var start = function ()
		{
			var inc = document.getElementById('content');
			var wsImpl = window.WebSocket || window.MozWebSocket;
			// if browser supports websocket
			if (wsImpl != null)
			{
				inc.innerHTML += "connecting to server ..<br/>";

				// create a new websocket and connect
				window.ws = new wsImpl('ws://localhost:27879/');

				// when data is comming from the server, this metod is called
				ws.onmessage = function (evt)
				{
					var server = $.parseJSON(evt.data);
					var valor = server.ServerValue;
					var temp = [now += updateInterval, valor];
					if (myData.length <= 100)
					{
						myData.push(temp);
					}
					else
					{
						myData.shift();
					}
				};

				// when the connection is established, this method is called
				ws.onopen = function ()
				{
					inc.innerHTML += '.. connection open<br/>';
				};

				// when the connection is closed, this method is called
				ws.onclose = function ()
				{
					inc.innerHTML += '.. connection closed<br/>';
				}
			}
			else
			{
				inc.innerHTML = "This browser doesn't support WebSockets!";
			}
		}
		window.onload = start;

		var options =
		{
			series:
			{
				lines:
				{
					show: true,
					lineWidth: 1.2,
					fill: true
				}
			},
			xaxis:
			{
				mode: "time",
				tickSize: [2, "second"],
				tickFormatter: function (v, axis)
				{
					var date = new Date(v);

					if (date.getSeconds() % 20 == 0)
					{
						var hours = date.getHours() < 10 ? "0" + date.getHours() : date.getHours();
						var minutes = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
						var seconds = date.getSeconds() < 10 ? "0" + date.getSeconds() : date.getSeconds();

						return hours + ":" + minutes + ":" + seconds;
					} else
					{
						return "";
					}
				},
				axisLabel: "Time",
				axisLabelUseCanvas: true,
				axisLabelFontSizePixels: 12,
				axisLabelFontFamily: 'Verdana, Arial',
				axisLabelPadding: 10
			},
			yaxis:
			{
				min: 0,
				max: 100,
				tickSize: 5,
				tickFormatter: function (v, axis)
				{
					if (v % 10 == 0)
					{
						return v;
					}
					else
					{
						return "";
					}
				},
				axisLabel: "Connections",
				axisLabelUseCanvas: true,
				axisLabelFontSizePixels: 12,
				axisLabelFontFamily: 'Verdana, Arial',
				axisLabelPadding: 6
			},
			legend:
			{
				labelBoxBorderColor: "#fff"
			},
			grid:
			{
				backgroundColor: "#000000",
				tickColor: "#008040"
			}
		};

		$(document).ready(function ()
		{
			//dataset = [{ label: "CPU", data: data, color: "#00FF00" }];
			dataset = [{ label: serverName, data: myData, color: "#00FF00" }];
			$.plot($("#placeholder"), dataset, options);
			
			function update()
			{
				$.plot($("#placeholder"), dataset, options);
				setTimeout(update, updateInterval);
			}

			update();
		});
	</script>
}

Codetag.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>@ViewBag.Title - CodeTag Hiring Test</title>
		<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
		<meta name="viewport" content="width=device-width" />
		@Styles.Render("~/Content/css")
		@Scripts.Render("~/bundles/modernizr")
		@RenderSection("headScripts", required: false)
	</head>
	<body>
		@*<header>
			<div class="content-wrapper">
				<div class="float-left">
					<p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
				</div>
				<div class="float-right">
					<section id="login">
						@Html.Partial("_LoginPartial")
					</section>
					<nav>
						<ul id="menu">
							<li>@Html.ActionLink("Server Graphic", "Create", "Server")</li>
						</ul>
					</nav>
				</div>
			</div>
		</header>*@
		<div id="body">
			@RenderSection("featured", required: false)
			<section class="content-wrapper main-content clear-fix">
				@RenderBody()
			</section>
		</div>
		<footer>
			<div class="content-wrapper">
				<div class="float-left">
					<p>&copy; @DateTime.Now.Year - CodeTag Hiring Test</p>
				</div>
			</div>
		</footer>

		@Scripts.Render("~/bundles/jquery")
		@RenderSection("scripts", required: false)
	</body>
</html>